apps/main/urls.py
from django.urls import path
from main.views import mound, dashboard, organization, farm, field, machine, module, bale, laboratory

urlpatterns = [
    path('', dashboard.index, name='home'),
    path('organizations', organization.list, name='organization-list'),
    path('farms', farm.list, name='farms-list'),
    path('farms-json', farm.json_list, name='farms-list-json'),
    path('fields', field.list, name='fields-list'),
    path('machines', machine.list, name='machines-list'),
    path('modules', module.list, name='modules-list'),
    path('fields/<str:uid>/modules', module.fields, name='field-modules'),
    path('mounds', mound.list, name='mounds-list'),
    path('mounds/create', mound.create, name='mounds-create'),
    path('mounds/create-all', mound.create_all, name='mounds-create-all'),
    path('mounds/edit/<int:id>', mound.update, name='mounds-edit'),
    path('mounds/remove/<int:id>', mound.remove, name='mounds-remove'),
    path('mounds/modules/<int:id>', mound.modules, name='mounds-modules'),
    path('mound/start/production/<int:id>', mound.start_process, name='mounds-start-production'),
    path('mound/modules/json/<int:id>', bale.mound_module, name='bale-mound-modules'),
    path('bales', bale.list, name='bales-list'),
    path('bales/production/<int:mound_id>/<int:module_id>', bale.production, name='bales-production'),
    path('bales/production/<int:mound_id>', bale.production, name='bales-production'),
    path('bales/production', bale.production, name='bales-production'),
    path('laboratory/modules', laboratory.list, name='laboratory-modules'),
    path('laboratory/modules/moisture/<str:serial_number>', laboratory.moisture_update, name='laboratory-moisture')
]

config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from api.urls import urlpatterns as rest_urlpatterns
from rest_framework_swagger.views import get_swagger_view

api_title = 'Silverleafe HID Cotton API documentation'
schema_view = get_swagger_view(title=api_title, patterns=rest_urlpatterns, url='/api/v1/')

urlpatterns = [
    path('', include('tracking.urls')),
    path('app/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include('api.urls')),
    path('api/v1/', schema_view),
    path('', include('johndeere.urls')),
]

apps/main/models.py
from datetime import datetime
import uuid

from django.db import models
from django.utils.translation import ugettext_lazy as _
from core.models import BaseModel
from main.managers.bale import BaleManager
from main.managers.farm import FarmManager
from main.managers.field import FieldManager
from main.managers.module import ModuleManager
from main.managers.module_trace import ModuleTraceManager
from main.managers.mound import MoundManager


def year_choices():
    return [r for r in range(datetime.today().year-10, datetime.today().year+1)]


class Country(BaseModel):
    code = models.CharField(_('Country code'), max_length=3, blank=True)
    name = models.CharField(_('Country name'), max_length=255, blank=False)

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')

    def __str__(self):
        return self.name


class Region(BaseModel):
    code = models.CharField(_('Region code'), max_length=50, blank=False)
    name = models.CharField(max_length=255, blank=False)
    country = models.ForeignKey(Country, related_name='regions', null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')

    def __str__(self):
        return self.name


class District(BaseModel):
    code = models.CharField(_('District code'), max_length=50, blank=False)
    name = models.CharField(_('District name'), max_length=255, blank=False)
    region = models.ForeignKey(Region, related_name='districts', null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return self.name


class Organization(BaseModel):
    name = models.CharField(_('Organization name'), max_length=255, blank=False, null=False)
    type = models.CharField(_('Organization type'), max_length=255, blank=True, null=True)
    john_deere_id = models.IntegerField(_('John Deere Id'))
    member = models.BooleanField(_('Member'), default=False)
    internal = models.BooleanField(_('Internal'), default=False)

    class Meta:
        verbose_name = _('Organization')
        verbose_name_plural = _('Organizations')

    def __str__(self):
        return self.name


class Farm(BaseModel):
    name = models.CharField(_('Farm name'), max_length=300, blank=False, null=False)
    description = models.TextField(_('About farm'), blank=True, null=True)
    district = models.ForeignKey(District, related_name='farms', null=True, on_delete=models.SET_NULL)
    john_deere_id = models.CharField(_('John Deere Id'), max_length=255, blank=True, null=True)
    archived = models.BooleanField(default=False)

    objects = FarmManager()

    class Meta:
        verbose_name = _('Farm')
        verbose_name_plural = _('Farms')

    def __str__(self):
        return self.name


class Field(BaseModel):
    name = models.CharField(_('Field name'), max_length=300, blank=False, null=False)
    varieties = models.IntegerField(_('Varieties'), default=1, blank=True, null=True)
    farm = models.ForeignKey(Farm, verbose_name=_('Farm'), related_name='fields', null=True, on_delete=models.SET_NULL)
    geo_json = models.TextField(_('GeoJson'), blank=False)
    john_deere_id = models.CharField(_('John Deere Id'), max_length=255, blank=True, null=True)
    archived = models.BooleanField(default=False)
    last_modified_time = models.DateTimeField(_('Last Modified Time'))
    farm_uid = models.CharField(_('Farm UID'), max_length=255, blank=True, null=True)

    objects = FieldManager()

    class Meta:
        verbose_name = _('Field')
        verbose_name_plural = _('Fields')

    def __str__(self):
        return self.name

    def get_farm(self):
        return self.farm.name


class Equipment(BaseModel):
    name = models.CharField(_('Name'), max_length=255, blank=False, null=False)
    guid = models.CharField(_('GUID'), max_length=100, blank=False, null=False)
    john_deere_id = models.CharField(_('John Deere Id'), max_length=255, blank=True, null=True)
    description = models.TextField(_('Description'), blank=False)
    equipment_make = models.CharField(_('Equipment make name'), max_length=255, blank=True, null=True)
    equipment_make_erid = models.CharField(_('Equipment make ERID'), max_length=255, blank=True, null=True)
    equipment_type = models.CharField(_('Equipment type'), max_length=255, blank=True, null=True)
    equipment_type_guid = models.CharField(_('Equipment type GUID'), max_length=255, blank=True, null=True)
    equipment_type_id = models.CharField(_('Equipment type ID'), max_length=50, blank=True, null=True)
    equipment_apex_type = models.CharField(_('Equipment apex type'), max_length=255, blank=True, null=True)
    equipment_apex_type_guid = models.CharField(_('Equipment apex type GUID'), max_length=255, blank=True, null=True)
    equipment_apex_type_id = models.CharField(_('Equipment apex type ID'), max_length=50, blank=True, null=True)
    equipment_model = models.CharField(_('Equipment model'), max_length=255, blank=True, null=True)
    equipment_model_guid = models.CharField(_('Equipment model GUID'), max_length=255, blank=True, null=True)
    equipment_model_id = models.CharField(_('Equipment model ID'), max_length=255, blank=True, null=True)
    vin = models.CharField(_('Vin'), max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = _('Equipment')
        verbose_name_plural = _('Equipments')

    def __str__(self):
        return self.name


class Mound(BaseModel):

    class State(models.IntegerChoices):
        NEW = 1
        IN_PROCESS = 2
        PROCESSED = 3
        ARCHIVED = 4

    uid = models.CharField(_('UID'), max_length=100, blank=False, null=False)
    name = models.CharField(_('Name'), max_length=255, blank=False, null=False)
    mound_weight = models.FloatField(_('Mound weight'), default=0, null=True)
    farm = models.ForeignKey(Farm, verbose_name=_('Farm'), related_name='mounds', null=True, on_delete=models.SET_NULL)
    field = models.ForeignKey(Field, verbose_name=_('Field'), related_name='mounds', null=True,
                              on_delete=models.SET_NULL)
    start_production_time = models.DateTimeField(_('Start production timestamp'), null=True)
    end_production_time = models.DateTimeField(_('End production timestamp'), null=True)
    archived_time = models.DateTimeField(_('Removed timestamp'), null=True)
    state = models.IntegerField(choices=State.choices, default=State.NEW)

    objects = MoundManager()

    class Meta:
        verbose_name = _('Mound')
        verbose_name_plural = _('Mounds')

    def __str__(self):
        return self.name


class Module(BaseModel):

    class State(models.IntegerChoices):
        NEW = 1
        IN_PROCESS = 2
        PROCESSED = 3

    uid = models.CharField(_('ModuleID'), max_length=100, blank=False, null=False)
    serial_number = models.CharField(_('Serial number'), max_length=100, blank=True, null=True)
    wrap_lat = models.FloatField(_('Wrap lat'), null=True)
    wrap_long = models.FloatField(_('Wrap long'), null=True)
    wrap_date_time = models.DateTimeField(_('Wrap datetime'))
    data_ingestion_date = models.DateTimeField(_('Data ingestion date'))
    tag_count = models.IntegerField(_('Tag count'))
    variety_name = models.CharField(_('Variety name'), max_length=255, blank=True, null=True)
    machine_pin = models.CharField(_('Machine pin'), max_length=255, blank=True, null=True)
    operator = models.CharField(_('Operator'), max_length=255, blank=True, null=True)
    moisture = models.FloatField(_('Moisture'), null=True)
    moisture_unit = models.CharField('Moisture unit', max_length=100, blank=True, null=True)
    diameter = models.FloatField(_('Diameter'), blank=True, null=True)
    diameter_unit = models.CharField('Diameter unit', max_length=100, blank=True, null=True)
    weight = models.FloatField(_('Weight'), blank=True, null=True)
    weight_unit = models.CharField('Weight unit', max_length=100, blank=True, null=True)
    drop_lat = models.FloatField(_('Drop lat'), null=True)
    drop_long = models.FloatField(_('Drop long'), null=True)
    incremental_area = models.FloatField(_('Incremental area'), null=True)
    area_unit = models.CharField('Area unit', max_length=100, blank=True, null=True)
    field_uid = models.CharField(_('Field UID'), max_length=100, blank=True, null=True)
    farm = models.ForeignKey(Farm, verbose_name=_('Farm'), related_name='modules', null=True, on_delete=models.SET_NULL)
    field = models.ForeignKey(Field, verbose_name=_('Field'), related_name='modules', null=True,
                              on_delete=models.SET_NULL)
    equipment = models.ForeignKey(Equipment, verbose_name=_('Equipment'), related_name='modules', null=True,
                                  on_delete=models.SET_NULL)
    mound = models.ForeignKey(Mound, verbose_name=_('Mound'), related_name='modules', null=True, on_delete=models.SET_NULL)
    load_time = models.DateTimeField(_('Loaded to mound time'), null=True)
    start_production = models.DateTimeField(_('Start production timestamp'), null=True)
    end_production = models.DateTimeField(_('End production timestamp'), null=True)
    state = models.IntegerField(choices=State.choices, default=State.NEW)
    register_in_field_time = models.DateTimeField(_('Register on field'), null=True)
    in_field_lat = models.FloatField(_('In field lat'), null=True)
    in_field_long = models.FloatField(_('In field long'), null=True)
    picked_from_field_time = models.DateTimeField(_('Picked from field'), null=True)
    pick_lat = models.FloatField(_('Pick lat'), null=True)
    pick_long = models.FloatField(_('Pick long'), null=True)

    objects = ModuleManager()

    class Meta:
        verbose_name = _('Module')
        verbose_name_plural = _('Modules')

    def __str__(self):
        return f'{self.uid}'

    def get_farm(self):
        return self.farm.name

    def get_field(self):

apps/main/views/bale.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render

from main.forms import ProductionForm
from main.models import Bale, Module, Mound, ModuleTrace


@login_required
def list(request):
    bales = Module.objects.filter(state=Module.State.PROCESSED).order_by('-end_production').per_page(request, 20)
    return render(request, "main/bale/list.html", {'data': bales})


@login_required
def production(request, mound_id=None, module_id=None):

    mound = Mound.objects.get(id=mound_id) if mound_id is not None else None
    module_trace_query = ModuleTrace.objects.filter(mound_uid=mound.uid).filter(state__lt=ModuleTrace.State.PROCESSED)

    module_trace = module_trace_query.order_by('-time').first()
    bales = Bale.objects.filter(mound_id=mound_id).order_by('-id')

    form = ProductionForm(initial={'mound': mound, 'module_trace': module_trace})
    # form.fields['mound'].disabled = True
    # form.fields['module'].queryset = modules_query.order_by('-load_time')
    # form.fields['module'].disabled = True
    form.fields['module_trace'].queryset = module_trace_query.order_by('-time')

    if request.method == 'POST':
        form = ProductionForm(request.POST)
        if form.is_valid():
            module = form.instance.module_trace
            bales_count = module.bales.count()
            next_bale = bales_count + 1

            if bales_count == 0:
                module.start_production = datetime.datetime.now()
                module.state = Module.State.IN_PROCESS

            if next_bale >= 3:
                module.end_production = datetime.datetime.now()
                module.state = Module.State.PROCESSED

            module.save()

            form.instance.uid = f"UZB057{module.serial_number}{next_bale}{module.time.year}"
            form.save()

            if mound.modules.filter(state__lt=Module.State.PROCESSED).count() == 0:
                mound.state = mound.State.PROCESSED
                mound.end_production_time = datetime.datetime.now()
                mound.save()

            return HttpResponseRedirect(request.path_info)

    return render(request, "main/bale/production.html", {'form': form, 'bales': bales})


@login_required
def mound_module(request, id):
    modules = Module.objects.filter(mound_id=id).filter(state__lt=Module.State.PROCESSED).order_by('-load_time')
    serialized = serializers.serialize('json', modules)
    return JsonResponse(serialized, safe=False)


@login_required
def print_bale(request):
    pass

apps/main/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    return render(request, "main/index.html")

apps/main/views/farm.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render

from main.models import Farm


@login_required
def list(request):
    data = Farm.objects.all().order_by('id').per_page(request, 10)
    return render(request, "main/farm/list.html", {'data': data})


@login_required
def json_list(request):
    data = Farm.objects.all().order_by('id').values()
    # serializer = FarmSerializer(data)
    # data = serializers.serialize('json', data)
    return JsonResponse({
        'recordsTotal': 0,
        'recordsFiltered': 0,
        'data': data})

apps/main/views/field.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from main.models import Field


@login_required
def list(request):
    data = Field.objects.get_has_modules().order_by('-modules_count').per_page(request, 10)
    return render(request, "main/fields.html", {'data': data})

apps/main/views/laboratory.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from main.models import ModuleTrace


@login_required
def list(request):
    modules = ModuleTrace.objects.get_reception_modules().per_page(request, 10)
    return render(request, "main/laboratory/list.html", {'data': modules})


@login_required
def moisture_update(request, serial_number):
    module = get_object_or_404(ModuleTrace, serial_number=serial_number)
    module.moisture = request.POST.get('value', 0)
    module.save()
    return HttpResponse('')

apps/main/views/machine.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from main.models import Equipment


@login_required
def list(request):
    machines = Equipment.objects.all().order_by('id')
    return render(request, "main/machines.html", {'data': machines})

apps/main/views/organization.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from main.models import Organization


@login_required
def list(request):
    organizations = Organization.objects.all().order_by('id')
    return render(request, "main/organizations.html", {'data': organizations})

templates/main/bale/list.html
{% extends 'layout/base.html' %}
{% block content %}
    <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
    <link href="https://printjs-4de6.kxcdn.com/print.min.css" rel="stylesheet" type="text/css" />
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Bales</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
{#                        <div class="col-sm-12">#}
{#                            <div class="text-sm-end mt-2 mt-sm-0">#}
{#                                <a href="{% url 'bales-production' %}" class="btn btn-warning waves-effect waves-light">#}
{#                                    <i class="mdi mdi-plus-circle me-1"></i> Start production#}
{#                                </a>#}
{#                            </div>#}
{#                        </div><!-- end col-->#}
                    </div>

                    <div class="table-responsive">
                        <table class="table table-centered table-nowrap table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Farm</th>
                                <th>Field</th>
                                <th>Module serial Number</th>
                                <th>Start timestamp</th>
                                <th>Module weight</th>
                                <th>Unique gin bale</th>
                                <th>Gin weight</th>
                                <th>Finish timestamp</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for d in data %}
                                <tr>
                                    <td>{{ d.farm.name }}</td>
                                    <td>{{ d.field.name }}</td>
                                    <td>{{ d.uid }}</td>
                                    <td>{{ d.start_production }}</td>
                                    <td>{{ d.weight }}</td>
                                    <td>
                                        {% for bale in d.bales.all %}
                                            <p>{{ bale.uid }}</p>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% for bale in d.bales.all %}
                                            <p>{{ bale.weight }}</p>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% for bale in d.bales.all %}
                                            <p>{{ bale.print_date }}</p>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    {% include 'layout/pagination.html' with data=data %}

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
{% endblock %}

{% block customjs %}
    <script type="text/javascript">
    $(document).ready(function () {
        $('.qrcode_block').each(function (){
            let qr = $(this).data('uid');
            let div_id = "qrcode_" + qr;
            new QRCode(div_id, {
                text: qr,
                width: 100,
                height: 100,
                colorDark : "#000000",
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.L
            });
        });

        $('body').on('click', '.print_qr', function(){
            printJS($(this).data('id'), 'html')
        });
    });
    </script>
{% endblock %}

templates/main/bale/production.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
    <link href="https://printjs-4de6.kxcdn.com/print.min.css" rel="stylesheet" type="text/css" />
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'bales-list' %}">Bales</a></li>
                    </ol>
                </div>
                <h4 class="page-title">Production bales</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <button id="fetch_weight" class="btn btn-lg btn-success waves-effect waves-light">Get weight</button>
                    <button id="close_port" class="btn btn-lg btn-warning waves-effect waves-light">Close port</button>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="button-list pe-xl-6 d-grid">
                            <button type="submit" class="btn btn-lg btn-primary waves-effect waves-light">Add and print label</button>
                        </div>
                    </form>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col -->

        <div class="col-9">
            <div class="card">
                <div class="card-body">
                    <h4>Bales of {{ form.mound.initial }}</h4>
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Module</th>
                                <th>Unique ID</th>
                                <th>Weight</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for bale in bales %}
                            <tr>
                                <td>{{ bale.module }}</td>
                                <td>{{ bale.uid }}</td>
                                <td>{{ bale.weight }}</td>
                                <td>
                                    <div style="display: none;">
                                        <div id="print_{{ bale.uid }}" style="display: flex;">
                                            <div class="qrcode_block" id="qrcode_{{ bale.uid }}" data-uid="{{ bale.uid }}"></div>
                                            <div style="margin-left: 20px; text-align: center;">
                                                <img src="{% static 'assets/images/splash_screen_2_dark.png' %}" alt="" class="logo-light" height="64"/>
                                                <div>S/N: {{ bale.uid }}</div>
                                            </div>
                                        </div>
                                    </div>

                                    <a href="#" class="btn btn-success print_qr" data-id="print_{{ bale.uid }}"><i class="fa fa-print"></i> Print</a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
{% endblock %}

{% block customjs %}
    <script type="text/javascript">
    $(document).ready(function() {
        $('.select').select2();
        let mound_id = $('#id_mound').val();
        //update_modules(mound_id);

        $('.qrcode_block').each(function (){
            let qr = $(this).data('uid');
            let div_id = "qrcode_" + qr;
            new QRCode(div_id, {
                text: qr,
                width: 100,
                height: 100,
                colorDark : "#000000",
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.L
            });
        });

        $('body').on('click', '.print_qr', function(){
            printJS($(this).data('id'), 'html')
        });
    });

    $('body').on('change', '#id_mound', function (e){
        update_modules(this.value);
        console.log(this.value);
    });

    function update_modules(id){
        $.ajax({
          url: "/mound/modules/json/" + id,
        }).done(function(data) {
            let jsonData = JSON.parse(data);
            $('#id_module').html("");
            $.each(jsonData, function(index, value){
                let option = new Option(value.fields.uid, value.pk, true, true);
                $('#id_module').append(option);

            });
        });
    }
    </script>

    <script type="text/javascript">

    class LineBreakTransformer {
      constructor() {
        // A container for holding stream data until a new line.
        this.chunks = "";
      }

      transform(chunk, controller) {
        // Append new chunks to existing chunks.
        this.chunks += chunk;
        // For each line breaks in chunks, send the parsed lines out.
        const lines = this.chunks.split("\r\n");
        this.chunks = lines.pop();
        lines.forEach((line) => controller.enqueue(line));
      }

      flush(controller) {
        // When the stream is closed, flush any remaining chunks out.
        controller.enqueue(this.chunks);
      }
    }

    const textDecoder = new TextDecoderStream();


    if ("serial" in navigator) {
      console.log("Serial avialable");
    }

    document.querySelector('#fetch_weight').addEventListener('click', async () => {
      // const filters = [
      //   { usbVendorId: 1659, usbProductId: 8963 }
      // ];
      const port = await navigator.serial.requestPort();

      console.log(port.getInfo());

      await port.open({ baudRate: 9600, stopBits: 1, dataBits: 8, bufferSize: 8 });

      const textDecoder = new TextDecoderStream();
      const readableStreamClosed = port.readable.pipeTo(textDecoder.writable);
      //const reader = textDecoder.readable.getReader();
      const reader = textDecoder.readable
        .pipeThrough(new TransformStream(new LineBreakTransformer()))
        .getReader();

      document.querySelector('#close_port').addEventListener('click', async ()=>{
        await reader.cancel();
        await readableStreamClosed.catch(() => { /* Ignore the error */ });
        await port.close();
      });

      // Listen to data coming from the serial device.
      while (true) {
        const { value, done } = await reader.read();
        if (done) {
          // Allow the serial port to be closed later.
          reader.releaseLock();
          break;
        }
        // value is a string.
        console.log(value);
        let floatValue = value.match(/Net.+(\d+[,.]\d+)/)[1].replace(',', '.');
        console.log(floatValue);
        document.querySelector('#id_weight').value = floatValue;
      }

    });

  </script>
{% endblock %}